import { Lang } from '../types';

export const COLORS = ['#1E40AF', '#F8AF24', '#EF4444', '#10B981', '#6366F1', '#8B5CF6'];

export const TRANSLATIONS: Record<string, Record<Lang, string>> = {
  app_name: { en: 'Pictures Talk', th: 'Pictures Talk' },
  untitled: { en: 'Untitled Project', th: 'โปรเจกต์ไม่มีชื่อ' },
  file: { en: 'File', th: 'ไฟล์' },
  edit: { en: 'Edit', th: 'แก้ไข' },
  view: { en: 'View', th: 'มุมมอง' },
  export: { en: 'Export', th: 'ส่งออก' },
  canvas_title: { en: 'Creative Canvas', th: 'แคนวาสสร้างสรรค์' },
  canvas_desc: {
    en: 'Build visual summaries with shapes, text, icons, and reusable layouts.',
    th: 'สร้างงานสรุปแบบภาพด้วยรูปทรง ข้อความ ไอคอน และเลย์เอาต์ที่นำกลับมาใช้ซ้ำได้',
  },
  canvas_tool_title: { en: 'Canvas', th: 'แคนวาส' },
  canvas_tool_desc: {
    en: 'Manage the canvas workspace and layout.',
    th: 'จัดการพื้นที่ทำงานและเลย์เอาต์ของแคนวาส',
  },
  canvas_workspace_label: { en: 'Visual Workspace', th: 'พื้นที่ทำงานภาพ' },
  canvas_toolbar_label: { en: 'Tool Library', th: 'คลังเครื่องมือ' },
  canvas_toolbar_desc: {
    en: 'Choose a tool, then click or drag into the canvas.',
    th: 'เลือกเครื่องมือ แล้วคลิกหรือลากลงบนแคนวาส',
  },
  canvas_selection_label: { en: 'Selection Ready', th: 'พร้อมแก้ไขวัตถุ' },
  canvas_selection_desc: {
    en: 'Select an object to edit colors, type, and stroke settings.',
    th: 'เลือกวัตถุเพื่อปรับสี ตัวอักษร และเส้นขอบ',
  },
  canvas_empty_title: { en: 'Start with a tool or template', th: 'เริ่มจากเครื่องมือหรือเทมเพลต' },
  canvas_empty_desc: {
    en: 'Use the left toolbar to add shapes, text, icons, images, or templates. You can also drag items directly onto the canvas.',
    th: 'ใช้แถบเครื่องมือด้านซ้ายเพื่อเพิ่มรูปทรง ข้อความ ไอคอน รูปภาพ หรือเทมเพลต และลากวางลงบนแคนวาสได้ทันที',
  },
  canvas_empty_step_tools: { en: 'Pick a tool', th: 'เลือกเครื่องมือ' },
  canvas_empty_step_tools_desc: {
    en: 'Open Shapes, Text, Icons, Images, or Templates from the left rail.',
    th: 'เปิด Shapes, Text, Icons, Images หรือ Templates จากแถบด้านซ้าย',
  },
  canvas_empty_step_add: { en: 'Add to canvas', th: 'เพิ่มลงแคนวาส' },
  canvas_empty_step_add_desc: {
    en: 'Click to insert at center, or drag into position for faster placement.',
    th: 'คลิกเพื่อเพิ่มตรงกลาง หรือจะลากไปวางในตำแหน่งที่ต้องการก็ได้',
  },
  canvas_empty_step_edit: { en: 'Refine details', th: 'ปรับรายละเอียด' },
  canvas_empty_step_edit_desc: {
    en: 'Use the right panel to adjust size, color, background, and typography.',
    th: 'ใช้แผงด้านขวาเพื่อปรับขนาด สี พื้นหลัง และตัวอักษร',
  },
  canvas_drop_hint: { en: 'Drop items anywhere on the canvas', th: 'ลากวางองค์ประกอบได้ทุกจุดบนแคนวาส' },
  canvas_panel_canvas: { en: 'Canvas Settings', th: 'ตั้งค่าแคนวาส' },
  canvas_panel_selection: { en: 'Selected Object', th: 'วัตถุที่เลือก' },
  canvas_panel_canvas_desc: {
    en: 'Adjust the page size and background for the whole layout.',
    th: 'ปรับขนาดหน้าและพื้นหลังของงานทั้งหมด',
  },
  canvas_panel_selection_desc: {
    en: 'Refine the currently selected item.',
    th: 'ปรับแต่งวัตถุที่กำลังเลือกอยู่',
  },
  canvas_shapes_helper: {
    en: 'Click once to add at center or drag onto the canvas.',
    th: 'คลิกเพื่อเพิ่มตรงกลาง หรือจะลากลงบนแคนวาสก็ได้',
  },
  canvas_templates_helper: {
    en: 'Choose a layout to scaffold your slide instantly.',
    th: 'เลือกเลย์เอาต์เพื่อขึ้นโครงงานได้ทันที',
  },
  canvas_text_helper: {
    en: 'Use presets for quick title and body blocks.',
    th: 'ใช้รูปแบบข้อความสำเร็จรูปเพื่อเริ่มจัดวางได้เร็วขึ้น',
  },
  canvas_properties_toggle: { en: 'Toggle properties panel', th: 'สลับแผงคุณสมบัติ' },
  canvas_loading: { en: 'Syncing canvas...', th: 'กำลังซิงก์แคนวาส...' },
  canvas_items: { en: 'items', th: 'รายการ' },
  canvas_status_saved: { en: 'Autosave active', th: 'บันทึกอัตโนมัติเปิดอยู่' },
  canvas_status_focus: { en: 'Canvas is the main workspace', th: 'แคนวาสคือพื้นที่ทำงานหลัก' },
  canvas_properties_hint: {
    en: 'Canvas controls stay available. Selection controls appear when you pick an object.',
    th: 'การตั้งค่าแคนวาสจะแสดงเสมอ และการตั้งค่าวัตถุจะปรากฏเมื่อมีการเลือกวัตถุ',
  },
  canvas_quick_actions: { en: 'Quick Start', th: 'เริ่มต้นอย่างเร็ว' },
  canvas_dimensions_label: { en: 'Canvas Size', th: 'ขนาดแคนวาส' },
  canvas_size_custom: { en: 'Set a custom workspace size in pixels.', th: 'กำหนดขนาดพื้นที่ทำงานเองเป็นพิกเซล' },
  canvas_size_presets: { en: 'Presets', th: 'ขนาดสำเร็จรูป' },
  canvas_size_presets_desc: { en: 'Choose a common format to resize the canvas quickly.', th: 'เลือกขนาดมาตรฐานเพื่อปรับแคนวาสได้ทันที' },
  canvas_ratio_locked: { en: 'Width and height stay in sync.', th: 'ค่ากว้างและสูงจะปรับสัมพันธ์กัน' },
  canvas_ratio_unlocked: { en: 'Width and height can change independently.', th: 'ค่ากว้างและสูงสามารถปรับแยกกันได้' },
  canvas_ratio_lock_action: { en: 'Lock ratio', th: 'ล็อกสัดส่วน' },
  canvas_background_desc: { en: 'Pick the background color for the whole canvas.', th: 'เลือกสีพื้นหลังของแคนวาสทั้งหมด' },
  canvas_preset_square: { en: 'Square', th: 'จัตุรัส' },
  canvas_preset_presentation: { en: 'Presentation', th: 'งานนำเสนอ' },
  canvas_preset_classic: { en: 'Classic', th: 'คลาสสิก' },
  canvas_preset_story: { en: 'Story', th: 'สตอรี่' },
  canvas_ratio_square: { en: '1:1 ratio', th: 'สัดส่วน 1:1' },
  canvas_ratio_wide: { en: '16:9 ratio', th: 'สัดส่วน 16:9' },
  canvas_ratio_classic: { en: '4:3 ratio', th: 'สัดส่วน 4:3' },
  canvas_ratio_story: { en: '9:16 ratio', th: 'สัดส่วน 9:16' },
  canvas_background_label: { en: 'Background', th: 'พื้นหลัง' },
  canvas_object_label: { en: 'Object Style', th: 'สไตล์วัตถุ' },
  properties: { en: 'Properties', th: 'คุณสมบัติ' },
  dimensions: { en: 'Dimensions', th: 'ขนาด' },
  width_short: { en: 'W', th: 'กว้าง' },
  height_short: { en: 'H', th: 'สูง' },
  appearance: { en: 'Appearance', th: 'ลักษณะ' },
  fill: { en: 'Fill', th: 'สีเติม' },
  stroke: { en: 'Stroke', th: 'เส้นขอบ' },
  typography: { en: 'Typography', th: 'ตัวอักษร' },
  aspect_ratio: { en: 'Aspect ratio', th: 'อัตราส่วน' },
  background: { en: 'Background', th: 'พื้นหลัง' },
  text_color: { en: 'Text color', th: 'สีข้อความ' },
  shape_color: { en: 'Shape fill', th: 'สีรูปทรง' },
  apply: { en: 'Apply', th: 'ใช้สี' },
  regular: { en: 'Regular', th: 'ปกติ' },
  bold: { en: 'Bold', th: 'ตัวหนา' },
  semibold: { en: 'Semibold', th: 'กึ่งหนา' },
  normal: { en: 'Normal', th: 'ปกติ' },
  heading: { en: 'Heading', th: 'หัวข้อ' },
  subheading: { en: 'Subheading', th: 'หัวข้อรอง' },
  body_text: { en: 'Body Text', th: 'เนื้อหา' },
  shapes_title: { en: 'Shapes', th: 'รูปทรง' },
  shapes_desc: {
    en: 'Add basic geometric shapes like squares, circles, and triangles.',
    th: 'เพิ่มรูปทรงพื้นฐาน เช่น สี่เหลี่ยม วงกลม และสามเหลี่ยม',
  },
  connect_title: { en: 'Connect', th: 'เชื่อมต่อ' },
  connect_desc: {
    en: 'Create links and relationship lines between objects.',
    th: 'สร้างเส้นเชื่อมและความสัมพันธ์ระหว่างวัตถุ',
  },
  pencil_title: { en: 'Pencil', th: 'ดินสอ' },
  pencil_desc: { en: 'Freehand drawing and sketching tool.', th: 'เครื่องมือวาดเส้นอิสระและสเก็ตช์' },
  text_title: { en: 'Text', th: 'ข้อความ' },
  text_desc: { en: 'Insert headings, body text, or annotations.', th: 'แทรกหัวข้อ เนื้อหา หรือคำอธิบายประกอบ' },
  icons_title: { en: 'Icons', th: 'ไอคอน' },
  icons_desc: { en: 'Browse and add professional icons.', th: 'เลือกดูและเพิ่มไอคอนระดับมืออาชีพ' },
  images_title: { en: 'Images', th: 'รูปภาพ' },
  images_desc: { en: 'Upload your own images or search for stock photos.', th: 'อัปโหลดรูปของคุณเองหรือค้นหารูปภาพสต็อก' },
  templates_title: { en: 'Templates', th: 'เทมเพลต' },
  templates_desc: { en: 'Start quickly with pre-designed layouts.', th: 'เริ่มต้นได้รวดเร็วด้วยเลย์เอาต์ที่ออกแบบไว้แล้ว' },
  search_placeholder: { en: 'Search assets...', th: 'ค้นหาทรัพยากร...' },
  search_fonts_placeholder: { en: 'Search fonts', th: 'ค้นหาฟอนต์' },
  upload_btn: { en: 'Upload Image', th: 'อัปโหลดรูปภาพ' },
  upload_failed: { en: 'Upload failed. Please try again.', th: 'อัปโหลดไม่สำเร็จ กรุณาลองใหม่อีกครั้ง' },
  color: { en: 'Color', th: 'สี' },
  add_color: { en: 'Add color', th: 'เพิ่มสี' },
  confirm: { en: 'Confirm', th: 'ยืนยัน' },
  cancel: { en: 'Cancel', th: 'ยกเลิก' },
  no_shapes_found: { en: 'No shapes found', th: 'ไม่พบรูปทรงที่ค้นหา' },
  no_fonts_found: { en: 'No fonts found', th: 'ไม่พบฟอนต์ที่ค้นหา' },
};
