import { Lang } from '../types';

export const COLORS = ['#1E40AF', '#F8AF24', '#EF4444', '#10B981', '#6366F1', '#8B5CF6'];

export const TRANSLATIONS: Record<string, Record<Lang, string>> = {
  app_name: { en: 'Pictures Talk', th: 'Pictures Talk' },
  untitled: { en: 'Untitled Project', th: 'โปรเจกต์ไม่มีชื่อ' },
  file: { en: 'File', th: 'ไฟล์' },
  edit: { en: 'Edit', th: 'แก้ไข' },
  view: { en: 'View', th: 'มุมมอง' },
  export: { en: 'Export', th: 'ส่งออก' },
  canvas_title: { en: 'Creative Canvas', th: 'แคนวาสสร้างสรรค์' },
  canvas_desc: { en: 'Your visual playground. Select a tool from the left to start drawing, or use the Gemini AI bar below to generate concepts instantly.', th: 'พื้นที่สร้างสรรค์ของคุณ เลือกเครื่องมือด้านซ้ายเพื่อเริ่มวาด หรือใช้ Gemini AI เพื่อสร้างแนวคิดทันที' },
  canvas_tool_title: { en: 'Canvas', th: 'ผืนผ้าใบ' },
  canvas_tool_desc: { en: 'Manage the canvas workspace and layout.', th: 'จัดการพื้นที่ผืนผ้าใบและเลย์เอาต์' },
  properties: { en: 'Properties', th: 'คุณสมบัติ' },
  dimensions: { en: 'Dimensions', th: 'ขนาด' },
  width_short: { en: 'W', th: 'กว้าง' },
  height_short: { en: 'H', th: 'สูง' },
  appearance: { en: 'Appearance', th: 'ลักษณะ' },
  fill: { en: 'Fill', th: 'เติมสี' },
  stroke: { en: 'Stroke', th: 'เส้นขอบ' },
  typography: { en: 'Typography', th: 'ตัวอักษร' },
  regular: { en: 'Regular', th: 'ปกติ' },
  bold: { en: 'Bold', th: 'ตัวหนา' },
  semibold: { en: 'Semibold', th: 'กึ่งหนา' },
  normal: { en: 'Normal', th: 'ปกติ' },
  heading: { en: 'Heading', th: 'หัวข้อ' },
  subheading: { en: 'Subheading', th: 'หัวข้อรอง' },
  body_text: { en: 'Body Text', th: 'เนื้อหา' },
  shapes_title: { en: 'Shapes', th: 'รูปทรง' },
  shapes_desc: { en: 'Add basic geometric shapes like squares, circles, and triangles.', th: 'เพิ่มรูปทรงพื้นฐาน เช่น สี่เหลี่ยม วงกลม และสามเหลี่ยม' },
  connect_title: { en: 'Connect', th: 'เชื่อมต่อ' },
  connect_desc: { en: 'Create links and relationship lines between objects.', th: 'สร้างลิงก์และเส้นความสัมพันธ์ระหว่างวัตถุ' },
  pencil_title: { en: 'Pencil', th: 'ดินสอ' },
  pencil_desc: { en: 'Freehand drawing and sketching tool.', th: 'เครื่องมือวาดภาพและสเก็ตช์อิสระ' },
  text_title: { en: 'Text', th: 'ข้อความ' },
  text_desc: { en: 'Insert headings, body text, or annotations.', th: 'ใส่หัวข้อ เนื้อหา หรือคำอธิบาย' },
  icons_title: { en: 'Icons', th: 'ไอคอน' },
  icons_desc: { en: 'Browse and add thousands of professional icons.', th: 'เรียกดูและเพิ่มไอคอนระดับมืออาชีพหลายพันรายการ' },
  images_title: { en: 'Images', th: 'รูปภาพ' },
  images_desc: { en: 'Upload your own images or search for stock photos.', th: 'อัปโหลดรูปภาพของคุณเองหรือค้นหารูปภาพสต็อก' },
  templates_title: { en: 'Templates', th: 'เทมเพลต' },
  templates_desc: { en: 'Start quickly with pre-designed layouts.', th: 'เริ่มต้นอย่างรวดเร็วด้วยเลย์เอาต์ที่ออกแบบไว้ล่วงหน้า' },
  search_placeholder: { en: 'Search assets...', th: 'ค้นหาทรัพยากร...' },
  upload_btn: { en: 'Upload Image', th: 'อัปโหลดรูปภาพ' },
  upload_failed: { en: 'Upload failed. Please try again.', th: 'อัปโหลดไม่สำเร็จ กรุณาลองใหม่อีกครั้ง' },
  color: { en: 'Color', th: 'สี' },
  add_color: { en: 'Add color', th: 'เพิ่มสี' },
  confirm: { en: 'Confirm', th: 'ยืนยัน' },
  cancel: { en: 'Cancel', th: 'ยกเลิก' },
};
